# yaml-language-server: $schema=../../tools/schemas/jrtcctl.schema.json

# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: FirstExample

decoder:
  - type: decodergrpc
    port: 20789
    
app:
  - name: app1
    path: ${JRTC_PATH}/sample_apps/first_example_c/first_example_converted.py
    type: python
    port: 3001
    modules:
      - ${JRTC_PATH}/sample_apps/jbpf_codelets/data_generator/generated_data.py
      - ${JRTC_PATH}/sample_apps/jbpf_codelets/data_generator_2/generated_data_2.py
      - ${JRTC_PATH}/sample_apps/jbpf_codelets/simple_input/simple_input.py

jbpf:
  device:
    - id: 1
      port: 8080

  codelet_set:
    - device: 1
      config: ${JRTC_PATH}/sample_apps/jbpf_codelets/data_generator/codeletset.yaml

    - device: 1
      config: ${JRTC_PATH}/sample_apps/jbpf_codelets/data_generator_2/codeletset.yaml

    - device: 1
      config: ${JRTC_PATH}/sample_apps/jbpf_codelets/simple_input/codeletset.yaml
